### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [AntonGepting/tmux-interface-rs#18]
Hello, is this project still maintained? To be clear I am not judging the pace the software is being worked on, I like how such a library exists as I was thinking about using it, however if its not maintained I am worried I should not use it.
The last commit was 7 months ago, so is this normal? is the projected unmaintained or you wish to take a break from this project (any of these are ok obviously, I'm just curious)

**Comment by AntonGepting** [comment]
Hello, 

thank you for your interest. 

The library is not abandoned, but I apologize for the slower progress due to the implementation of other project and lack of inspiration and sufficient time for it.

If you are planning to use it, I believe you can still count on relative quick bug fixes and responses in case of serious problems (depends on the complexity and the size of the code, of course).

However you use it on your own risk with no warranties of any kind. Thank you for your understanding.
