### ISSUE TITLE
Typo in run-shell

### ISSUE THREAD

**Issue by Ganneff** [AntonGepting/tmux-interface-rs#9]
https://github.com/AntonGepting/tmux-interface-rs/blob/7a1dea0ad658e2cb8743311480d207ad1d196a48/src/commands/miscellaneous/run_shell.rs#L43

Should be background()

**Comment by AntonGepting** [comment]
Hello,

thank you for choosing/using the library. There could be more typing mistakes like this and even worse problems. Unfortunately detected in `if_shell()` too.

You can try to use `hotfix` branch instead of `main` if you want this update right now or just wait for the next version.

Thank you for reporting!

**Comment by Ganneff** [comment]
Thanks. I just wait for the next release. I only spotted it, I don't use the background() part of run_shell, (I'm mostly opening windows/panes and setting some options, depending on what user wants. Porting my old shell script to Rust (https://github.com/Ganneff/tm) and your tmux-interface made it much easier to do so. Thanks for that!)

**Comment by AntonGepting** [comment]
Awesome! If you have any other problems or suggestions while using the library, please feel free to contact me.

**Comment by AntonGepting** [comment]
fixed in [v0.3.0](https://github.com/AntonGepting/tmux-interface-rs/tree/v0.3.0)

thank you, and sorry about long waiting time
